renderPath = "tmpl"
[default]
   pathRadiant = "."
   pathAnt = "."
[[descriptor]]
    module = "controllers"
    srcName = "radical_default_controller.go.tmpl"
    dstPath = "{{pathRadiant}}/controllers/radical_default_controller.go"
    once = true
[[descriptor]]
    module = "controllers"
    srcName = "controller.go.tmpl"
    dstPath = "{{pathRadiant}}/controllers/{{modelName}}.go"
[[descriptor]]
    module = "models"
    srcName = "radical_default_model.go.tmpl"
    dstPath = "{{pathRadiant}}/models/radical_default_model.go"
    once = true
[[descriptor]]
    module = "models"
    srcName = "model.go.tmpl"
    dstPath = "{{pathRadiant}}/models/{{modelName}}.go"
[[descriptor]]
    module = "routers"
    srcName = "router.go.tmpl"
    dstPath = "{{pathRadiant}}/routers/{{modelName}}.go"
[[descriptor]]
    module = "antList"
    srcName = "list.tsx.tmpl"
    dstPath = "{{pathAnt}}/{{modelName}}/list.tsx"
[[descriptor]]
    module = "antForm"
    srcName = "formconfig.tsx.tmpl"
    dstPath = "{{pathAnt}}/{{modelName}}/formconfig.tsx"
[[descriptor]]
    module = "antCreate"
    srcName = "create.tsx.tmpl"
    dstPath = "{{pathAnt}}/{{modelName}}/create.tsx"
[[descriptor]]
    module = "antUpdate"
    srcName = "update.tsx.tmpl"
    dstPath = "{{pathAnt}}/{{modelName}}/update.tsx"
[[descriptor]]
    module = "antInfo"
    srcName = "info.tsx.tmpl"
    dstPath = "{{pathAnt}}/{{modelName}}/info.tsx"
[[descriptor]]
    module = "antUp"
    srcName = "up.sql.tmpl"
    dstPath = "{{pathRadiant}}/sql/{{modelName}}_up.sql"
    script = "radical pro migration --sql={{pathRadiant}}/sql/{{modelName}}_up.sql"
[[descriptor]]
    module = "antDown"
    srcName = "down.sql.tmpl"
    dstPath = "{{pathRadiant}}/sql/{{modelName}}_down.sql"


